// <auto-generated />
namespace LibraryManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AcademyComputer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AcademyComputer));
        
        string IMigrationMetadata.Id
        {
            get { return "201907041519277_AcademyComputer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
